# Github Docker container action to build the binary
name: 'Build binary'
description: 'Build the binary in a Docker container'
inputs:
  arch:
    description: 'Build architecture'
    required: true
    default: 'linux-aarch64'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arch }}
    - ${{ github.repositoryUrl}}
    - ${{ github.ref_name }}